"""Remove owner from cake

Revision ID: 2e04bc5ffae3
Revises: f2f01008b494
Create Date: 2021-11-10 07:47:44.167575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e04bc5ffae3'
down_revision = 'f2f01008b494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cake_owner_id_fkey', 'cake', type_='foreignkey')
    op.drop_column('cake', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cake', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cake_owner_id_fkey', 'cake', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
