"""Add user to cake table auto

Revision ID: ae9f0a0b54f4
Revises: 261013dde9a2
Create Date: 2021-11-09 17:54:01.044007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9f0a0b54f4'
down_revision = '261013dde9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cake_description'), 'cake', ['description'], unique=False)
    op.create_index(op.f('ix_cake_id'), 'cake', ['id'], unique=False)
    op.create_index(op.f('ix_cake_title'), 'cake', ['title'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_cake_title'), table_name='cake')
    op.drop_index(op.f('ix_cake_id'), table_name='cake')
    op.drop_index(op.f('ix_cake_description'), table_name='cake')
    op.drop_table('cake')
    # ### end Alembic commands ###
