"""Remove owner from cake_2

Revision ID: cc4858d9a987
Revises: 2e04bc5ffae3
Create Date: 2021-11-10 07:50:22.955016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4858d9a987'
down_revision = '2e04bc5ffae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
